"use strict";
const canvas=document.getElementById("gameCanvas"),context=canvas.getContext("2d"),scoreElement=document.getElementById("score"),highScoreElement=document.getElementById("highScore"),speedElement=document.getElementById("speed"),overlay=document.getElementById("overlay"),overlayTitle=document.getElementById("overlayTitle"),overlayText=document.getElementById("overlayText"),startButton=document.getElementById("startButton"),soundButton=document.getElementById("soundButton");
const GRID_SIZE=20,CELL_SIZE=canvas.width/GRID_SIZE,STARTING_SNAKE=[{x:9,y:10},{x:8,y:10},{x:7,y:10}],DIRECTIONS={up:{x:0,y:-1},down:{x:0,y:1},left:{x:-1,y:0},right:{x:1,y:0}};
let snake=[...STARTING_SNAKE],food={x:14,y:10},direction=DIRECTIONS.right,queuedDirection=DIRECTIONS.right,score=0,highScore=Number(localStorage.getItem("snake-high-score"))||0,gameState="ready",lastStep=0,animationFrame=0,soundEnabled=true,audioContext;
highScoreElement.textContent=highScore;
function resetGame(){snake=STARTING_SNAKE.map(part=>({...part}));direction=DIRECTIONS.right;queuedDirection=DIRECTIONS.right;score=0;scoreElement.textContent="0";speedElement.textContent="1×";placeFood();draw()}
function startGame(){resetGame();gameState="playing";overlay.classList.add("hidden");lastStep=performance.now();cancelAnimationFrame(animationFrame);animationFrame=requestAnimationFrame(gameLoop)}
function gameLoop(timestamp){if(gameState!=="playing")return;const interval=Math.max(65,145-Math.floor(score/4)*7);if(timestamp-lastStep>=interval){update();draw();lastStep=timestamp}animationFrame=requestAnimationFrame(gameLoop)}
function update(){direction=queuedDirection;const head={x:snake[0].x+direction.x,y:snake[0].y+direction.y};const hitWall=head.x<0||head.x>=GRID_SIZE||head.y<0||head.y>=GRID_SIZE;const hitSelf=snake.some(part=>part.x===head.x&&part.y===head.y);if(hitWall||hitSelf){endGame();return}snake.unshift(head);if(head.x===food.x&&head.y===food.y){score+=1;scoreElement.textContent=score;speedElement.textContent=`${Math.min(3,1+Math.floor(score/8)*.5)}×`;playTone(540,.07);placeFood()}else snake.pop()}
function placeFood(){const emptyCells=[];for(let y=0;y<GRID_SIZE;y+=1)for(let x=0;x<GRID_SIZE;x+=1)if(!snake.some(part=>part.x===x&&part.y===y))emptyCells.push({x,y});food=emptyCells[Math.floor(Math.random()*emptyCells.length)]}
function draw(){context.fillStyle="#0d1511";context.fillRect(0,0,canvas.width,canvas.height);context.strokeStyle="rgba(189,255,217,.045)";context.lineWidth=1;for(let i=1;i<GRID_SIZE;i+=1){const offset=i*CELL_SIZE;context.beginPath();context.moveTo(offset,0);context.lineTo(offset,canvas.height);context.moveTo(0,offset);context.lineTo(canvas.width,offset);context.stroke()}drawFood();snake.forEach((part,index)=>drawSnakePart(part,index))}
function drawSnakePart(part,index){const gap=2.5,x=part.x*CELL_SIZE+gap,y=part.y*CELL_SIZE+gap,size=CELL_SIZE-gap*2;context.fillStyle=index===0?"#89ffc0":`hsl(147 78% ${57-Math.min(index,18)}%)`;roundedRect(x,y,size,size,index===0?9:7);context.fill();if(index===0){context.fillStyle="#092216";const horizontal=direction.x!==0,eyeOne=horizontal?{x:x+size*.7,y:y+size*.3}:{x:x+size*.3,y:y+size*.7},eyeTwo={x:x+size*.7,y:y+size*.7};[eyeOne,eyeTwo].forEach(eye=>{context.beginPath();context.arc(eye.x,eye.y,2.3,0,Math.PI*2);context.fill()})}}
function drawFood(){const centerX=food.x*CELL_SIZE+CELL_SIZE/2,centerY=food.y*CELL_SIZE+CELL_SIZE/2+1;context.shadowColor="rgba(255,86,86,.55)";context.shadowBlur=16;context.fillStyle="#ff6d6d";context.beginPath();context.arc(centerX-4,centerY,8.7,0,Math.PI*2);context.arc(centerX+4,centerY,8.7,0,Math.PI*2);context.fill();context.shadowBlur=0;context.strokeStyle="#73db8e";context.lineWidth=3;context.beginPath();context.moveTo(centerX,centerY-7);context.quadraticCurveTo(centerX+4,centerY-15,centerX+10,centerY-13);context.stroke()}
function roundedRect(x,y,width,height,radius){context.beginPath();context.roundRect(x,y,width,height,radius)}
function endGame(){gameState="ended";playTone(150,.18);if(score>highScore){highScore=score;localStorage.setItem("snake-high-score",String(highScore));highScoreElement.textContent=highScore;overlayTitle.textContent="Kỷ lục mới!"}else overlayTitle.textContent="Thua rồi!";overlayText.textContent=`Bạn ghi được ${score} điểm. Chơi lại và phá kỷ lục nhé!`;startButton.textContent="Chơi lại";overlay.classList.remove("hidden")}
function togglePause(){if(gameState==="playing"){gameState="paused";overlayTitle.textContent="Đã tạm dừng";overlayText.textContent="Nhấn Space hoặc nút bên dưới để tiếp tục.";startButton.textContent="Tiếp tục";overlay.classList.remove("hidden")}else if(gameState==="paused"){gameState="playing";overlay.classList.add("hidden");lastStep=performance.now();animationFrame=requestAnimationFrame(gameLoop)}}
function changeDirection(next){if(gameState==="ready"||gameState==="ended")startGame();if(gameState!=="playing")return;if(next.x+direction.x===0&&next.y+direction.y===0)return;queuedDirection=next}
function playTone(frequency,duration){if(!soundEnabled)return;audioContext||=new(window.AudioContext||window.webkitAudioContext)();const oscillator=audioContext.createOscillator(),gain=audioContext.createGain();oscillator.frequency.value=frequency;gain.gain.setValueAtTime(.08,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+duration);oscillator.connect(gain).connect(audioContext.destination);oscillator.start();oscillator.stop(audioContext.currentTime+duration)}
const keyMap={ArrowUp:DIRECTIONS.up,w:DIRECTIONS.up,W:DIRECTIONS.up,ArrowDown:DIRECTIONS.down,s:DIRECTIONS.down,S:DIRECTIONS.down,ArrowLeft:DIRECTIONS.left,a:DIRECTIONS.left,A:DIRECTIONS.left,ArrowRight:DIRECTIONS.right,d:DIRECTIONS.right,D:DIRECTIONS.right};
document.addEventListener("keydown",event=>{if(keyMap[event.key]){event.preventDefault();changeDirection(keyMap[event.key])}else if(event.code==="Space"){event.preventDefault();if(gameState==="ready"||gameState==="ended")startGame();else togglePause()}});
document.querySelectorAll("[data-direction]").forEach(button=>button.addEventListener("pointerdown",event=>{event.preventDefault();changeDirection(DIRECTIONS[button.dataset.direction])}));
startButton.addEventListener("click",()=>{if(gameState==="paused")togglePause();else startGame()});
soundButton.addEventListener("click",()=>{soundEnabled=!soundEnabled;soundButton.classList.toggle("muted",!soundEnabled);soundButton.setAttribute("aria-pressed",String(!soundEnabled))});
resetGame();
